# 비지도 학습_K-Means

In [16]:
# 꽃을 이용한 군집화

import pandas as pd
import plotly.express as px
#from sklearn.cluster import k_means

#데이터 불러오기
path = r"C:\Users\Jinho\work\iris_dataset.csv"

#데이터프레임 생성
df = pd.read_csv(path)

display(df)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## 꽃잎 길이와 넓이 관계시각화

In [17]:
fig = px.scatter(
    data_frame=df,
    x='petal width (cm)',
    y='petal length (cm)',
    color='label',
    title='꽃잎 관계 시각화'
)
fig.show()

## 군집화에 사용할 데이터 생성

In [18]:
# 꽃잎의 길이, 꽃잎의 넓이
wl_data = df[['petal length (cm)','petal width (cm)']]
#w_data = df['petal width (cm)']
display(wl_data)

     petal length (cm)  petal width (cm)
0                  1.4               0.2
1                  1.4               0.2
2                  1.3               0.2
3                  1.5               0.2
4                  1.4               0.2
..                 ...               ...
145                5.2               2.3
146                5.0               1.9
147                5.2               2.0
148                5.4               2.3
149                5.1               1.8

[150 rows x 2 columns]

### K-Means 이용한 군집화

In [ ]:
# 필요한 모델 클래스 임포트

from sklearn.cluster import KMeans

#2차원 2개 군집
model1 = KMeans(n_clusters=2,random_state=0)
#예측과 평가 
output1 = model1.fit_predict(wl_data)
print(output1)
#display(output1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

## 2-Days 비지도 학습(K-Means)

In [ ]:
#거리 기반 평균으로 경계선(기준선) 만든다.
import numpy as np
print("="*50)
#1의 군집이(몇개로 되어있는지)
label1 = output1[0:50]
#빈도수(항목,빈도수)
counts1 = np.unique(label1,return_counts=True)
print(f"1.군집화:{counts1}")
print("="*50)

#군집이(몇개로 되어있는지)
label2 = output1[50:]
counts2 = np.unique(label2,return_counts=True)
print(f"2.군집화:{counts2}")
print("="*50)

==================================================
1.군집화:(array([1], dtype=int32), array([50]))
==================================================
2.군집화:(array([0, 1], dtype=int32), array([99,  1]))
==================================================

## 군집화(n_clusters='3',PC3)

In [ ]:
from sklearn.cluster import KMeans
#군집: 3개  
model2 = KMeans(n_clusters=3,random_state=0)

#예측과 평가
output2 = model2.fit_predict(wl_data)

print(output2)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2
 2 2]

In [ ]:
#label1 = output2[0:50]
#빈도수(항목,빈도수)
counts1 = np.unique(output2,return_counts=True)
print(f"군집화 전체:{counts1}")
print("="*50)

#index: 0~49-> 군집화 종류와 군집별 개수
label1=output2[0:50]
counts2 = np.unique(label1,return_counts=True)
print(f"pc2.군집화:{counts2}")
print("="*50)

#index: 50~99-> 군집화 종류와 군집별 개수
label2=output2[50:100]
counts3 = np.unique(label2,return_counts=True)
print(f"pc2-3.군집화:{counts3}")

label3 = output2[100:]
counts4 = np.unique(label3,return_counts=True)
print(f"pc2-3.군집화:{counts4}")

#버지니카

군집화 전체:(array([0, 1, 2], dtype=int32), array([52, 50, 48]))
==================================================
pc2.군집화:(array([1], dtype=int32), array([50]))
==================================================
pc3.군집화:(array([0, 2], dtype=int32), array([48,  2]))
pc3.군집화:(array([0, 2], dtype=int32), array([ 4, 46]))

In [ ]:
#엘보우 
#x축: 군집 수
#SSE(오차제곱합):중심점 데이터,주변에 있는 오차 거리차 제곱 합계

## 최적의 클러스터 개수 설정

In [ ]:
# 1. SSE 측정
#############################################
# SSE보다 MSE(혹은 RMSE)를 더 자주 사용합니다
# SSE: 오차를 단순히 누적하여 합산한 값 (개수(n)가 많아질수록 무조건 값이 커진다)
# MSE (Mean Squared Error): SSE를 데이터 개수 n으로 나눈 평균 제곱 오차입니다. 
#############################################

## sse 저장용 빈 리스트 생성
sse = []

## x축(군집의 개수) 설정
clusters = range(1, 11)

## KMeans로 군집화 실행, 군집별 sse 추출 및 저장
for num in clusters:
    # num:1~10까지 
    model = KMeans(n_clusters=num, random_state=0)
    # (학습과 평가)
    model.fit_predict(wl_data)
    # SSE 값을 저장
    #최적의 군집 개수(K)를 눈으로 확인하기
    sse.append(model.inertia_)

print(f'sse 측정의 결과 : \n{sse}')
print('-' * 80)

# 2. plotly.express를 활용한 시각화
fig2 = px.line(
    x=clusters,
    y=sse,
    ## 꺾이는 지점(Elbow Point)을 명확하게 파악할 수 있도록 마커 추가
    markers=True,
    title='최적의 클러스터 개수 설정 : 엘보우(elbow) method',
    labels={'x': 'Number of Clusters (k)', 'y': 'SSE'}
)

fig2.show()

sse 측정의 결과 :
[550.8953333333333, 86.39021984551397, 31.37135897435897, 19.477123363965468, 14.130893864755937, 11.830278409090909, 9.826884351401379, 8.036281171442933, 6.761387045960576, 6.381007703081232]
--------------------------------------------------------------------------------