# AutoML

In [9]:
import pandas as pd

#데이터 불러오기
path = r"C:\Users\Jinho\work\Telco-Customer-Churn.csv"
df = pd.read_csv(path)

#데이터프레임 생성
display(df)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# 누락

In [10]:
#기본정보 확인
#df.info()
# object 

#TotalCharges 컬럼: 숫자로 변환할 수 없는 문자열 행 ->누락(NaN) 변환 ->제거
#문자열에서 숫자로 변환(X) 에러(X) 누락(O)
#문자열 행 -> 누락(NaN)으로 변환 
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors='coerce')

## 데이터프레임에 누락
df1 = df.dropna(ignore_index=True)
df2 = df1.drop(columns=['customerID'])
display(df1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

# 학습용 데이터와 평가용 데이터 생성

In [11]:
#비율(분할 X)
from sklearn.model_selection import train_test_split
#X,Y 분할 하지 않는다.

train_df,test_df = train_test_split(
    df2,
    test_size=0.2,
    random_state=0,
    stratify=df2['Churn']
)

In [14]:
#학습용 데이터, 결과 확인
print(f"학습용 데이터:",train_df.index)
print(f"평가용 데이터:",test_df.index)

#결과 비율
train_df_ratin = train_df['Churn'].value_counts(normalize=True)

학습용 데이터: Index([3780, 1588, 2927,  198, 4504,  275, 5802, 6393,  355, 2595,
       ...
        963, 1206, 3431, 2125, 2163, 6168, 4543, 3956, 6130, 6814],
      dtype='int64', length=5625)
평가용 데이터: Index([5126, 2423, 2498, 3114, 2529, 2428, 5089, 4429, 1983, 1418,
       ...
       3512, 1878, 3341,  649, 3598, 2351, 3637, 6703, 6618, 6010],
      dtype='int64', length=1407)

# 학습(모델 생성)

In [15]:
#필요한 클래스 임포트
from autogluon.tabular import TabularPredictor

predicter = TabularPredictor(label='Churn',eval_metric='accuracy',path='AutoGluon_Model')


predicter.fit(
    train_data=train_df,
    presets='best_quality',
    num_gpus=0,
    dynamic_stacking=False,
    num_stack_levels=1,
    time_limit=300
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.12.14
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26300
CPU Count:          20
Pytorch Version:    2.13.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       1.70 GB / 15.63 GB (10.9%)
Disk Space Avail:   398.41 GB / 952.65 GB (41.8%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "c:\Users\Jinho\work\AutoGluon_Model"
Train Data Rows:    5625
Train Data Columns: 19
Label Column:       Churn
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['No', 'Yes']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    1745.65 MB
	Train Data (Original)  Memory Usage: 4.61 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  :  2 | ['MonthlyCharges', 'TotalCharges']
		('int', [])    :  2 | ['SeniorCitizen', 'tenure']
		('object', []) : 15 | ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 10 | ['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', ...]
		('float', [])     :  2 | ['MonthlyCharges', 'TotalCharges']
		('int', [])       :  1 | ['tenure']
		('int', ['bool']) :  6 | ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', ...]
	0.3s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 0.22 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.33s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 108 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 199.73s of the 299.66s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=4.04%)
	0.7342	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 162.98s of the 262.91s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 18.96% memory usage per fold, 75.82%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=5, gpus=0, memory=18.96%)
	0.8043	 = Validation score   (accuracy)
	6.85s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 152.27s of the 252.20s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/1.8 GB
	0.7872	 = Validation score   (accuracy)
	1.41s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 150.55s of the 250.48s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/2.4 GB
	0.7863	 = Validation score   (accuracy)
	0.91s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 149.34s of the 249.27s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 16.93% memory usage per fold, 67.73%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=5, gpus=0, memory=16.93%)
	0.8078	 = Validation score   (accuracy)
	124.83s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 20.04s of the 119.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/2.7 GB
	0.7831	 = Validation score   (accuracy)
	2.28s	 = Training   runtime
	0.39s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 16.95s of the 116.89s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/2.7 GB
	0.7876	 = Validation score   (accuracy)
	2.71s	 = Training   runtime
	0.74s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 13.07s of the 113.00s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.11%)
	0.8043	 = Validation score   (accuracy)
	24.59s	 = Training   runtime
	0.34s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.67s of the 77.32s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/0.4 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	0.8078	 = Validation score   (accuracy)
	0.3s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 108 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 76.98s of the 76.92s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 17.24% memory usage per fold, 68.98%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=5, gpus=0, memory=17.24%)
	0.8101	 = Validation score   (accuracy)
	11.63s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 57.86s of the 57.80s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.60%)
	0.8123	 = Validation score   (accuracy)
	2.43s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 45.78s of the 45.73s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/1.7 GB
	0.8007	 = Validation score   (accuracy)
	2.45s	 = Training   runtime
	0.44s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 42.70s of the 42.64s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=20, gpus=0, mem=0.0/2.9 GB
	0.8	 = Validation score   (accuracy)
	1.65s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 40.73s of the 40.68s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 13.52% memory usage per fold, 54.10%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=5, gpus=0, memory=13.52%)
	0.8087	 = Validation score   (accuracy)
	41.15s	 = Training   runtime
	0.2s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 299.67s of the -5.72s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/2.5 GB
	Ensemble Weights: {'LightGBM_BAG_L2': 1.0}
	0.8123	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 308.81s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 842.2 rows/s (704 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (5625 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\Jinho\work\AutoGluon_Model")

In [16]:
#학습에 사용된 
leaderboard = predicter.leaderboard()
display(leaderboard)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBM_BAG_L2,0.812267,accuracy,2.161367,166.508609,0.100953,2.432635,2,True,11
1,WeightedEnsemble_L3,0.812267,accuracy,2.164886,166.880675,0.003518,0.372066,3,True,15
2,LightGBMXT_BAG_L2,0.810133,accuracy,2.123395,175.706420,0.062981,11.630446,2,True,10
3,CatBoost_BAG_L2,0.808711,accuracy,2.255719,205.229818,0.195305,41.153844,2,True,14
4,CatBoost_BAG_L1,0.807822,accuracy,0.116636,124.834872,0.116636,124.834872,1,True,5
5,WeightedEnsemble_L2,0.807822,accuracy,0.117635,125.130291,0.000998,0.295418,2,True,9
6,LightGBM_BAG_L1,0.804267,accuracy,0.054952,6.847291,0.054952,6.847291,1,True,2
7,NeuralNetFastAI_BAG_L1,0.804267,accuracy,0.336282,24.587683,0.336282,24.587683,1,True,8
8,RandomForestGini_BAG_L2,0.800711,accuracy,2.499177,166.524541,0.438763,2.448567,2,True,12
9,RandomForestEntr_BAG_L2,0.800000,accuracy,2.281487,165.722012,0.221072,1.646038,2,True,13
10,ExtraTreesEntr_BAG_L1,0.787556,accuracy,0.741582,2.706612,0.741582,2.706612,1,True,7
11,RandomForestGini_BAG_L1,0.787200,accuracy,0.192189,1.412297,0.192189,1.412297,1,True,3
12,RandomForestEntr_BAG_L1,0.786311,accuracy,0.192043,0.905280,0.192043,0.905280,1,True,4
13,ExtraTreesGini_BAG_L1,0.783111,accuracy,0.389725,2.279554,0.389725,2.279554,1,True,6
14,LightGBMXT_BAG_L1,0.734222,accuracy,0.037006,0.502384,0.037006,0.502384,1,True,1

In [18]:
#best 모델
best_model = predicter.model_best
print(best_model)

WeightedEnsemble_L3

In [ ]:
import warnings
## 평가용 데이터를 이용한 성능 평가
# evaluate() (예측과 평가 동시)
performance = predicter.evaluate(test_df)
print(f"고객 이탈 예측 데이터:{performance}")

#balanced accuracy: 정답별로 accuracy 평가 후 평균
#    accuracy(이탈 X) = 100%
#    accuracy(이탈 O) = 0%
#    평균 1 + 0 / 2


warnings.filterwarnings('ignore')

고객 이탈 예측 데이터:{'accuracy': 0.8031272210376688, 'balanced_accuracy': np.float64(0.6927916198601239), 'mcc': 0.44917751035899905, 'roc_auc': np.float64(0.8493873303963846), 'f1': 0.5525040387722132, 'precision': 0.6979591836734694, 'recall': 0.4572192513368984}

# 저장된 MD 이용하기

In [ ]:
#모델 지정 경로 설정
model_path = r"C:\Users\Jinho\work\AutoGluon_Model"

#저장된 모델(학습이 완료된 상태)  불러오기
loaded_pred = TabularPredictor.load(model_path)

In [26]:
#성능 평가
performance = loaded_pred.evaluate(test_df)
print("저장된 모델을 이용한 성능평가:",performance)

저장된 모델을 이용한 성능평가: {'accuracy': 0.8031272210376688, 'balanced_accuracy': np.float64(0.6927916198601239), 'mcc': 0.44917751035899905, 'roc_auc': np.float64(0.8493873303963846), 'f1': 0.5525040387722132, 'precision': 0.6979591836734694, 'recall': 0.4572192513368984}