# 비지도 학습_K-Means

In [ ]:
# 꽃을 이용한 군집화

import pandas as pd
import plotly.express as px
#from sklearn.cluster import k_means

#데이터 불러오기
path = r"C:\Users\Jinho\work\iris_dataset.csv"

#데이터프레임 생성
df = pd.read_csv(path)

display(df)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## 꽃잎 길이와 넓이 관계시각화

In [8]:
fig = px.scatter(
    data_frame=df,
    x='petal width (cm)',
    y='petal length (cm)',
    color='label',
    title='꽃잎 관계 시각화'
)
fig.show()

## 군집화에 사용할 데이터 생성

In [12]:
# 꽃잎의 길이, 꽃잎의 넓이
wl_data = df[['petal length (cm)','petal width (cm)']]
#w_data = df['petal width (cm)']
display(wl_data)

     petal length (cm)  petal width (cm)
0                  1.4               0.2
1                  1.4               0.2
2                  1.3               0.2
3                  1.5               0.2
4                  1.4               0.2
..                 ...               ...
145                5.2               2.3
146                5.0               1.9
147                5.2               2.0
148                5.4               2.3
149                5.1               1.8

[150 rows x 2 columns]

### K-Means 이용한 군집화

In [15]:
# 필요한 모델 클래스 임포트

from sklearn.cluster import KMeans

model1 = KMeans(n_clusters=2,random_state=0)

output1 = model1.fit_predict(wl_data)
print(output1)
#display(output1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]